### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ttxyy** [Michaelwucoc/Star-wall#1]
为什么这个地方显示成这样
![Screenshot_2024-01-06-19-04-38-749_myapp xingqiang-edit](https://github.com/Michaelwucoc/Star-wall/assets/155817760/6bd94e62-2359-4f28-952d-75f9f84a1589)

**Comment by Michaelwucoc** [comment]
本问题已经解决，感谢您的Issue
<img width="546" alt="image" src="https://github.com/Michaelwucoc/Star-wall/assets/110759450/f9ba1427-2ba8-48d0-8bca-63c433e77b33">
